name: weatherbox
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  get:
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  flutter_native_splash: ^2.2.17
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
      - asset: assets/fonts/Roboto/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto/Roboto-Light.ttf
        weight: 100
      - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        weight: 300
      - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        weight: 500

    - family: Nunito
      fonts:
      - asset: assets/fonts/Nunito/Nunito-Regular.ttf
      - asset: assets/fonts/Nunito/Nunito-Light.ttf
        weight: 100
      - asset: assets/fonts/Nunito/Nunito-Medium.ttf
        weight: 300
      - asset: assets/fonts/Nunito/Nunito-Bold.ttf
        weight: 500
        
  assets:
    - assets/images/aqi/
    - assets/images/sun_moon/
    - assets/images/uvindex/
    - assets/images/weather_icons/
    - assets/images/wind/