// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhuhuyRTs1UgT077Y3NP3O0f9u5d0VmrU',
    appId: '1:231172437837:web:0aca2047601baeb9502904',
    messagingSenderId: '231172437837',
    projectId: 'weatherbox-flutter',
    authDomain: 'weatherbox-flutter.firebaseapp.com',
    storageBucket: 'weatherbox-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP_328Q6gcBnb0wUMh5ZXHBbMDfMO-tXU',
    appId: '1:231172437837:android:71108cac96bd5d44502904',
    messagingSenderId: '231172437837',
    projectId: 'weatherbox-flutter',
    storageBucket: 'weatherbox-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUl42sJXHY0mUYp_k0pIXjWDByTS6BLsA',
    appId: '1:231172437837:ios:4fd7627fbeaf5301502904',
    messagingSenderId: '231172437837',
    projectId: 'weatherbox-flutter',
    storageBucket: 'weatherbox-flutter.appspot.com',
    iosClientId: '231172437837-42acpu4idtc4geojcj1g2neped8tupns.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUl42sJXHY0mUYp_k0pIXjWDByTS6BLsA',
    appId: '1:231172437837:ios:4fd7627fbeaf5301502904',
    messagingSenderId: '231172437837',
    projectId: 'weatherbox-flutter',
    storageBucket: 'weatherbox-flutter.appspot.com',
    iosClientId: '231172437837-42acpu4idtc4geojcj1g2neped8tupns.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherbox',
  );
}
